name: Terraform Deploy Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Initialize Terraform
        env:
          LINUX_HOST: ${{ secrets.LINUX_HOST }}
          LINUX_PORT: ${{ secrets.LINUX_PORT }}
          LINUX_USER: ${{ secrets.LINUX_USER }}
          LINUX_PASSWORD: ${{ secrets.LINUX_PASSWORD }}
        run: terraform init

      - name: Apply Terraform Plan
        env:
          TF_VAR_linux_host: ${{ secrets.LINUX_HOST }}
          TF_VAR_linux_port: ${{ secrets.LINUX_PORT }}
          TF_VAR_linux_user: ${{ secrets.LINUX_USER }}
          TF_VAR_linux_password: ${{ secrets.LINUX_PASSWORD }}
        run: terraform apply -auto-approve

      # Securely pass variables for sensitive information
      - name: Set Environment Variables
        run: |
          echo "TF_VAR_linux_host=${{ secrets.LINUX_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_linux_user=${{ secrets.LINUX_USER }}" >> $GITHUB_ENV
          echo "TF_VAR_linux_password=${{ secrets.LINUX_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_linux_port=${{ secrets.LINUX_PORT }}" >> $GITHUB_ENV
